import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";
import StatusBadge from "../components/StatusBadge";

export default function AssignmentDetails() {
  const { id } = useParams();
  const { user } = useAuth();
  const [assignment,setAssignment] = useState(null);
  const [content,setContent] = useState("");
  const [submissions,setSubmissions] = useState([]);
  const [message,setMessage] = useState("");

  const load = async () => {
    const {data} = await api.get(`/assignments/${id}`);
    setAssignment(data);
    if (user.role === "professor") {
      const r = await api.get(`/submissions/assignment/${id}`);
      setSubmissions(r.data);
    }
  };

  useEffect(()=>{ load().catch(e=>setMessage(e.response?.data?.message || "Unable to load")); },[id]);

  const submit = async e => {
    e.preventDefault();
    try {
      await api.post(`/submissions/${id}`, {content});
      setContent("");
      setMessage("Submitted successfully. The server calculated your status.");
      load();
    } catch(e) { setMessage(e.response?.data?.message || "Submission failed"); }
  };

  if (!assignment) return <section><p className="muted">{message || "Loading..."}</p></section>;

  return <section className="details">
    <div className="details-hero"><div><span className="subject">{assignment.subject}</span><h1>{assignment.title}</h1><p>{assignment.description || "No description provided."}</p></div><StatusBadge status={assignment.status}/></div>
    <div className="deadline-box"><strong>Deadline</strong><span>{new Date(assignment.deadline).toLocaleString()}</span></div>
    {message && <div className="success">{message}</div>}
    {user.role === "student" && !assignment.mySubmission && (
      <form className="panel" onSubmit={submit}><h2>Submit your solution</h2><p className="muted">Your submission timestamp is generated by the server.</p><textarea required rows="10" placeholder="Paste your solution, notes, or URL here..." value={content} onChange={e=>setContent(e.target.value)}></textarea><button className="primary">Submit assignment</button></form>
    )}
    {assignment.mySubmission && <div className="panel"><h2>Your submission</h2><StatusBadge status={assignment.mySubmission.status}/><p className="muted">Submitted at: {new Date(assignment.mySubmission.submittedAt).toLocaleString()}</p><div className="submission-content">{assignment.mySubmission.content}</div></div>}
    {user.role === "professor" && <div className="panel"><h2>Student submissions</h2>{submissions.length===0?<p className="muted">No submissions yet.</p>:submissions.map(s=><div className="submission-row" key={s._id}><div><strong>{s.student.name}</strong><p>{s.student.email}</p><small>{new Date(s.submittedAt).toLocaleString()}</small></div><StatusBadge status={s.status}/></div>)}</div>}
  </section>;
}
